[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "main"
version = "0.1.0"
description = "GIC DATA ENGINEER TAKE HOME PACKAGES"
authors = ["Poe Wun Lee <poewunlee@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "2.2.2"
dotenv = "^0.9.9"
pytest = "^9.0.2"