BEGIN TRANSACTION;
DROP TABLE IF EXISTS "fund_position";
CREATE TABLE IF NOT EXISTS "fund_position" (
    "FINANCIAL TYPE"    TEXT,
    "SYMBOL"    TEXT,
    "SECURITY NAME" TEXT,
    "SEDOL" TEXT,
    "ISIN" TEXT,
    "PRICE" REAL,
    "QUANTITY" REAL,
    "REALISED P/L" REAL,
    "MARKET VALUE" REAL,
    "FUND" TEXT,
    "DATETIME" TEXT
);
COMMIT;