WITH aggregated_fund AS (
	SELECT 
		fp.DATETIME, 
		fp.FUND, 
		SUM(fp.'MARKET VALUE') as CURRENT_TOTAL_MV, 
		SUM(fp.'REALISED P/L') AS CURRENT_TOTAL_PL
	FROM fund_position fp
	GROUP BY 1,2
),
previous_position as (
	SELECT *, 
		LAG(CURRENT_TOTAL_MV,1) OVER (PARTITION BY FUND ORDER BY DATETIME) AS PREVIOUS_TOTAL_MV,
		LAG(CURRENT_TOTAL_PL,1) OVER (PARTITION BY FUND ORDER BY DATETIME) AS PREVIOUS_TOTAL_PL
	FROM aggregated_fund
),
ror_cte as (
	SELECT 
		*, 
		(CURRENT_TOTAL_MV - PREVIOUS_TOTAL_MV + CURRENT_TOTAL_PL)/PREVIOUS_TOTAL_PL AS RATE_OF_RETURN
	FROM previous_position
)
SELECT 
	DATETIME, 
	FUND, 
	RATE_OF_RETURN, 
	CURRENT_TOTAL_MV, 
	PREVIOUS_TOTAL_MV, 
	CURRENT_TOTAL_PL, 
	PREVIOUS_TOTAL_PL
FROM(
	SELECT 
		*,
		RANK() OVER (PARTITION BY DATETIME ORDER BY RATE_OF_RETURN DESC) as ROR_RANK
	FROM ror_cte
)
WHERE ROR_RANK =1
AND RATE_OF_RETURN IS NOT NULL
;